### PR TITLE
Create id_reports.py

### PR DESCRIPTION
**Pull request by cdobs**
Creates id_reports.py which is a script that creates detailed reports for ingestion requests by querying the OOI M2M API with ingestion IDs. These reports include metadata about the ingestion process, number of files ingested, etc. This script can also be used to update the state of ingestion IDs, e.g., to change the state from "MOCK" to "RUN".

### CODE REVIEW

**Review by cwingard — CHANGES_REQUESTED** [review]
I ran into an error running this:
```
Traceback (most recent call last):
  File "/home/cwingard/anaconda3/envs/ooi/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-8ae068d575c7>", line 11, in <module>
    df = pd.DataFrame(j, index=[0])
  File "/home/cwingard/anaconda3/envs/ooi/lib/python3.7/site-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/cwingard/anaconda3/envs/ooi/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 257, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/cwingard/anaconda3/envs/ooi/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 82, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/home/cwingard/anaconda3/envs/ooi/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 323, in _homogenize
    val, index, dtype=dtype, copy=False, raise_cast_failure=False
  File "/home/cwingard/anaconda3/envs/ooi/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 712, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File "/home/cwingard/anaconda3/envs/ooi/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1233, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
```

If I changed the code starting on line 204 from:
```
# Store everything in a temporary dataframe
df = pd.DataFrame(j, index=[0])
df = df[['id', 'type', 'refDes_subsite', 'refDes_node', 'refDes_sensor', \
         'status', 'state', 'entryDate', 'username', 'dataSource', \
         'options_checkExistingFiles', 'parserDriver', 'fileMask']]
```
to:
```
# Store everything in a temporary dataframe
df = pd.DataFrame(j, index=[0], dtype=object)
df = df[['id', 'type', 'refDes_subsite', 'refDes_node', 'refDes_sensor',
         'status', 'state', 'entryDate', 'username', 'dataSource',
         'options_checkExistingFiles', 'parserDriver', 'fileMask']]
df = df.infer_objects()
```
everything worked fine (note, you don't need the `\` line continuation markers). I like this, I definitely approve with the small change above.

**Comment by cdobs** [comment]
Updated id_reports.py with @cwingard's comments. Thanks Chris!

**Review by cwingard — DISMISSED** [review]

**Comment by cdobs** [comment]
A id_reports result snuck into the PR and I deleted it, so I had to re-request your review. Sorry about that @cwingard

**Review by cwingard — DISMISSED** [review]

**Review by cwingard — APPROVED** [review]
This is a great tool that will help with managing the ingest requests. I approve!

**Review by reedan88 — APPROVED** [review]

**Comment by reedan88** [comment]
Looks good. You can go ahead and merge!

**Pull request merged**
